### ISSUE TITLE
Bank page on submit - Warning: Cannot modify header information

### ISSUE THREAD

**Issue by derby** [UnaiYecora/acf-recaptcha#3]
**! ! ! P L E A S E    H E L P ! ! !**

When saving an ACF field group which contains a recaptcha field AND when submitting an ACF fronted form the following error appears and there will only be a blank white page:

`Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/acf-recaptcha/acf-recaptcha-v5.php:254) in /wp-includes/pluggable.php on line 1228`

Thanks in advance and best regards

**Comment by derby** [comment]
OK I found the mistake:
Delete Lines 253 and 254 in acf-recaptcha-v5.php, so that **?>** is absolutely the last letter.

**Comment by UnaiYecora** [comment]
Alright, fixed and updated. Thank you very much @derby!
